version: '3.4'

services:
    telegram-parser:
        build:
            context: .
            dockerfile: ./Dockerfile
        network_mode: "host"
        environment:
            TELEGRAM_API_ID: ${TELEGRAM_API_ID}
            TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
            API_URL: ${API_URL:-https://localhost:7006/api/v1/telegram}
            WEBSOCKET_URL: ${WEBSOCKET_URL:-ws://localhost:7015/ws}
            WEBSOCKET_REALM: ${WEBSOCKET_REALM:-realm1}