version: '3.4'

services:
    python:
        build:
            context: .
            dockerfile: ./Dockerfile
        extra_hosts:
            - host.docker.internal:host-gateway
        environment:
            TELEGRAM_API_ID: ${TELEGRAM_API_ID}
            TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
            API_URL: ${API_URL:-https://host.docker.internal:7006/api/v1/telegram}
            WEBSOCKET_URL: ${WEBSOCKET_URL:-ws://host.docker.internal:7015}
            WEBSOCKET_REALM: ${WEBSOCKET_REALM:-realm1}