version: '3.4'

services:
    python:
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: unless-stopped
        env_file:
            - .env
            - .env.local
        extra_hosts:
            - host.docker.internal:host-gateway